version: '3.8'

services:
  web:
    image: nginx:latest
    platform: linux/amd64  
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # - ./html:/var/www/html
      - "/Users/panya/Project-ALL/randwad/html:/var/www/html"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: php
    volumes:
      # - ./html:/var/www/html
      - "/Users/panya/Project-ALL/randwad/html:/var/www/html"

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"

    volumes:
      # - mysql-data:/var/lib/mysql
      - /Users/panya/Project-ALL/mysql-data:/var/lib/mysql  # map volumes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

